- name: installing required system packages
  yum: pkg={{ item }} state=present
  sudo: yes
  with_items:
    - php
    - php-mysql
    - php-pecl-memcache
  notify:
    - restart apache
  tags:
    - apt