---
- name: Install nginx
  yum: name=nginx state=present

- name: Copy general nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf

- name: Copy nginx configuration for app
  template: src=front.conf.j2 dest=/etc/nginx/conf.d/front.conf
  
- name: Remove default ssl site
  command: rm /etc/nginx/conf.d/virtual.conf removes=/etc/nginx/conf.d/virtual.conf

- name: Remove virtial site
  command: rm /etc/nginx/conf.d/ssl.conf removes=/etc/nginx/conf.d/ssl.conf

- name: Remove default site
  command: rm /etc/nginx/conf.d/default.conf removes=/etc/nginx/conf.d/default.conf
  notify:
  - restart nginx