---
# Warby Parker Infrastructure

# common configuration
- hosts: all
  sudo: yes
  roles:
  - common

# configure and deploy the application server
- hosts: app
  sudo: yes
  roles:
  - iptables-app
  - apache
  - mysql
  - php

  
# configure and deploy the frontend servers.
- hosts: front
  sudo: yes
  roles:
  - iptables-proxy
  - nginx
  - memcached
