---
server_hostname: 'app'

# php.ini
php_max_execution_time: '90'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'On'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'
php_date_timezone: 'US/Central'

# my.cnf
mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
innodb_file_per_table: 'innodb_file_per_table'

# mysql
mysql_port: 3306
mysql_root_password: '1234infra'
mysql_infratest_password: 'infra1234'

# apache
apache_server_admin: 'david@davidneudorfer.com'
apache_server_alias: '*.*.dev'